from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest
from pathlib import Path


SOURCE_ROOT = Path(__file__).resolve().parents[1]


class AgentToolingTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary_directory.cleanup)
        self.repository = Path(self.temporary_directory.name) / "repository"
        shutil.copytree(SOURCE_ROOT / "agents", self.repository / "agents")
        shutil.copytree(SOURCE_ROOT / "scripts", self.repository / "scripts")

    def run_script(self, name: str, *arguments: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(self.repository / "scripts" / name), *arguments],
            cwd=self.repository,
            check=False,
            capture_output=True,
            text=True,
        )


class BuildAgentsTests(AgentToolingTestCase):
    def test_builds_global_profile_in_declared_order_and_skips_unchanged_output(self) -> None:
        first_result = self.run_script("build-agents", "global")

        self.assertEqual(first_result.returncode, 0, first_result.stderr)
        output_path = self.repository / "agents" / "dist" / "global" / "AGENTS.md"
        content = output_path.read_text(encoding="utf-8")
        manifest = tomllib.loads(
            (self.repository / "agents/profiles/global.toml").read_text(encoding="utf-8")
        )
        expected_version = re.escape(manifest["version"])
        self.assertRegex(
            content,
            re.compile(
                r"\A<!-- Generated by scripts/build-agents from "
                r"agents/profiles/global\.toml\. Do not edit directly\. -->\n"
                rf"<!-- Profile: global; version: {expected_version}; "
                r"source-sha256: [0-9a-f]{64} -->\n\n"
            ),
        )
        authority_position = content.index("# Authority Boundaries")
        todo_position = content.index("# TODO Files")
        maintenance_position = content.index("# Maintaining Agent Guidance")
        self.assertLess(authority_position, todo_position)
        self.assertLess(todo_position, maintenance_position)

        second_result = self.run_script("build-agents", "global")

        self.assertEqual(second_result.returncode, 0, second_result.stderr)
        self.assertIn("unchanged", second_result.stdout.lower())
        self.assertEqual(content, output_path.read_text(encoding="utf-8"))

    def test_rejects_fragment_paths_outside_the_fragment_directory(self) -> None:
        profile = self.repository / "agents" / "profiles" / "unsafe.toml"
        profile.write_text(
            """\
schema_version = 1
name = "unsafe"
version = "0.1.0"
description = "Unsafe fixture"
use_cases = ["Validation test"]
fragments = ["../README.md"]
""",
            encoding="utf-8",
        )

        result = self.run_script("build-agents", "unsafe")

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("outside agents/fragments", result.stderr)


class InstallGlobalTests(AgentToolingTestCase):
    def setUp(self) -> None:
        super().setUp()
        build_result = self.run_script("build-agents", "global")
        self.assertEqual(build_result.returncode, 0, build_result.stderr)
        self.generated = (
            self.repository / "agents" / "dist" / "global" / "AGENTS.md"
        )
        self.codex_home = Path(self.temporary_directory.name) / "codex-home"
        self.codex_home.mkdir()
        self.target = self.codex_home / "AGENTS.md"
        self.target.write_text("old guidance\n", encoding="utf-8")

    def test_dry_run_prints_diff_without_modifying_target(self) -> None:
        result = self.run_script(
            "install-global", "--codex-home", str(self.codex_home)
        )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.target.read_text(encoding="utf-8"), "old guidance\n")
        self.assertEqual(list(self.codex_home.glob("AGENTS.md.backup-*")), [])
        self.assertIn("-old guidance", result.stdout)
        self.assertIn("+# Authority Boundaries", result.stdout)
        self.assertIn("dry run", result.stdout.lower())

    def test_apply_backs_up_and_atomically_replaces_changed_target(self) -> None:
        result = self.run_script(
            "install-global", "--codex-home", str(self.codex_home), "--apply"
        )

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(
            self.target.read_text(encoding="utf-8"),
            self.generated.read_text(encoding="utf-8"),
        )
        backups = list(self.codex_home.glob("AGENTS.md.backup-*"))
        self.assertEqual(len(backups), 1)
        self.assertEqual(backups[0].read_text(encoding="utf-8"), "old guidance\n")
        self.assertLess(result.stdout.index("--- "), result.stdout.index("backup:"))
        self.assertLess(result.stdout.index("backup:"), result.stdout.index("installed:"))

    def test_apply_refuses_stale_generated_profile(self) -> None:
        self.generated.write_text(
            self.generated.read_text(encoding="utf-8") + "stale change\n",
            encoding="utf-8",
        )

        result = self.run_script(
            "install-global", "--codex-home", str(self.codex_home), "--apply"
        )

        self.assertNotEqual(result.returncode, 0)
        self.assertIn("generated global profile is stale", result.stderr)
        self.assertEqual(self.target.read_text(encoding="utf-8"), "old guidance\n")
        self.assertEqual(list(self.codex_home.glob("AGENTS.md.backup-*")), [])


class CheckGeneratedTests(AgentToolingTestCase):
    def setUp(self) -> None:
        super().setUp()
        build_result = self.run_script("build-agents", "global")
        self.assertEqual(build_result.returncode, 0, build_result.stderr)
        self.generated = (
            self.repository / "agents" / "dist" / "global" / "AGENTS.md"
        )

    def test_accepts_current_output_without_rewriting_it(self) -> None:
        fixed_timestamp = 1_000_000_000
        os.utime(self.generated, ns=(fixed_timestamp, fixed_timestamp))

        result = self.run_script("check-generated")

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("ok: agents/dist/global/AGENTS.md", result.stdout)
        self.assertEqual(self.generated.stat().st_mtime_ns, fixed_timestamp)

    def test_reports_stale_output_with_diff_without_rewriting_it(self) -> None:
        stale_content = self.generated.read_text(encoding="utf-8") + "stale change\n"
        self.generated.write_text(stale_content, encoding="utf-8")

        result = self.run_script("check-generated", "global")

        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertIn("stale: agents/dist/global/AGENTS.md", result.stdout)
        self.assertIn("-stale change", result.stdout)
        self.assertEqual(self.generated.read_text(encoding="utf-8"), stale_content)

    def test_reports_missing_output_without_creating_it(self) -> None:
        self.generated.unlink()

        result = self.run_script("check-generated", "global")

        self.assertEqual(result.returncode, 1, result.stderr)
        self.assertIn("missing: agents/dist/global/AGENTS.md", result.stdout)
        self.assertFalse(self.generated.exists())


if __name__ == "__main__":
    unittest.main()
